# Generated by Django 2.2.7 on 2021-01-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_auto_20210113_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteshare',
            name='note',
            field=models.FileField(upload_to='media/'),
        ),
    ]
