# Generated by Django 2.2.7 on 2021-01-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_auto_20210115_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshare',
            name='user_d',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to='notesapp.UserDetail'),
            preserve_default=False,
        ),
    ]
