# Generated by Django 2.2.7 on 2021-01-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0005_noteshare_user_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteshare',
            name='user_d',
        ),
        migrations.AlterField(
            model_name='noteshare',
            name='reciver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_id', to='notesapp.UserDetail'),
        ),
    ]
