# Generated by Django 2.2.7 on 2021-01-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0006_auto_20210115_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteshare',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='notesapp.UserDetail'),
        ),
    ]
